projectmanagement/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projectmanagement_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

handler403 = 'projectmanagement_app.views.custom_error_403'
handler404 = 'projectmanagement_app.views.custom_error_404'

projectmanagement_app/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path("", views.ProjectListView.as_view(), name="index"),
    path("project/<int:project_id>/tasks/", login_required(views.TaskListView.as_view()), name="task-list"),
    path("project/<int:project_id>/tasks/<int:pk>/", login_required(views.TaskDetailView.as_view()), name="task-detail"),
    path("project/<int:pk>/projectdetails/", login_required(views.ProjectDetailView.as_view()), name="project-detail"),
    path("projects/add/", views.ProjectCreate.as_view(), name="project-create"),
    path("project/<int:project_id>/tasks/add/", views.add_task, name="task-create"),
    path("managers/add/", views.ProjectManagerCreate.as_view(), name="projectmanager-create"),
    path("projects/<int:pk>/projectdetails/update/", views.ProjectUpdate.as_view(), name="project-update"),
    path("project/<int:project_id>/tasks/<int:pk>/update/", views.TaskUpdate.as_view(), name="task-update"),
    path("managers/<int:pk>/update", views.ProjectManagerUpdate.as_view(), name="projectmanager-update"),
    path("projects/<int:pk>/projectdetails/delete/", views.ProjectDelete.as_view(), name="project-delete"),
    path("project/<int:project_id>/tasks/<int:pk>/delete/", views.TaskDelete.as_view(), name="task-delete"),
    path("managers/<int:pk>/delete/", views.ProjectManagerDelete.as_view(), name="projectmanager-delete"),
    path("managers/", views.ProjectManagerListView.as_view(), name="projectmanager-list"),
    path("managers/<int:manager_id>/", login_required(views.managers_projects), name="managers-projects"),
    path("statistics/", login_required(views.statistics), name="statistics"),
]

projectmanagement_app/models.py
from django.db import models


class ProjectManager(models.Model):
    name = models.CharField(max_length=100)
    department = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Project(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(null=True, blank=True)
    manager = models.ForeignKey(ProjectManager, on_delete=models.PROTECT, null=True)

    PROJECT_STATUS = (
        ('NS', 'Not started'),
        ('IP', 'In Progress'),
        ('CO', 'Completed'),
        ('CA', 'Cancelled'),
    )

    status = models.CharField(
        max_length=2, 
        choices=PROJECT_STATUS, 
        default='NS',
    )

    def __str__(self):
        return self.name


class Task(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    due_date = models.DateField()

    TASK_STATUS = (
        ('NS', 'Not started'),
        ('IP', 'In Progress'),
        ('CO', 'Completed'),
        ('CA', 'Cancelled'),
    )

    status = models.CharField(
        max_length=2, 
        choices=TASK_STATUS, 
        default='NS',
    )
    
    person_assigned = models.CharField(max_length=100)
    additional_information = models.TextField(null=True, blank=True)

    PRIORITIES = (
        ('H', 'high'),
        ('M', 'medium'),
        ('L', 'low'),
    )

    priority = models.CharField(
        max_length=1, 
        choices=PRIORITIES, 
        default='M',
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["due_date"]

projectmanagement_app/forms.py
from django.forms import ModelForm, DateInput
from .models import Task
from django.core.exceptions import ValidationError
import datetime

class TaskForm(ModelForm):
    class Meta:
        model = Task

        fields = [
        "project",
        "name",
        "due_date",
        "status",
        "person_assigned",
        "additional_information",
        "priority",
    ]

        widgets = {
        'due_date': DateInput(format=('%m/%d/%Y'), attrs={'type':'date'}),
            }

    def clean_due_date(self):
        data = self.cleaned_data['due_date']
        if data < datetime.date.today():
            raise ValidationError('Invalid date - due date in past')
        return data

projectmanagement_app/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Project, ProjectManager, Task
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from .forms import TaskForm
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import permission_required, login_required


class ProjectListView(ListView):
    model = Project
    paginate_by = 7
        

class TaskListView(ListView):
    model = Task
    paginate_by = 7

    def get_queryset(self):
        return Task.objects.filter(project_id=self.kwargs["project_id"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        project_name = Project.objects.get(id=self.kwargs["project_id"])
        project_id = self.kwargs["project_id"]
        context["project_name"] = project_name
        context["project_id"] = project_id
        return context


class ProjectManagerListView(ListView):
    model = ProjectManager
    paginate_by = 7


class ProjectDetailView(DetailView):
    model = Project

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        num_completed_tasks = Task.objects.filter(status='CO').filter(project_id=self.kwargs["pk"]).count()
        num_tasks = Task.objects.filter(project_id=self.kwargs["pk"]).count()
        if num_tasks:
            percent_completed_tasks = "{:.0%}".format(num_completed_tasks/num_tasks)
            context["percent_completed_tasks"] = percent_completed_tasks
        project_id = self.kwargs["pk"]
        context["project_id"] = project_id
        context["num_tasks"] = num_tasks
        context["num_completed_tasks"] = num_completed_tasks
        return context


class TaskDetailView(DetailView):
    model = Task

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        project_id = self.kwargs["project_id"]
        task_id = self.kwargs["pk"]
        context["project_id"] = project_id
        context["task_id"] = task_id
        return context
    

class ProjectCreate(PermissionRequiredMixin, CreateView):
    permission_required = 'projectmanagement_app.add_project'
    model = Project
    fields = [
        "name", 
        "description", 
        # "department", 
        "manager", 
        "status",
    ]

    def get_success_url(self):
        return reverse("index")

@login_required
@permission_required('projectmanagement_app.add_task', raise_exception=True)
def add_task(request, project_id):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('task-list', args=(project_id,)))
    else:
        form = TaskForm(initial={"project": project_id})

    context = {
            'form': form,
            'project_id': project_id,
        }

# 
    return render(request, "add_task.html", context)


class ProjectManagerCreate(PermissionRequiredMixin, CreateView):
    permission_required = 'projectmanagement_app.add_projectmanager'
    model = ProjectManager
    fields = [
        "name", 
        "department",
    ]

    def get_success_url(self):
        return reverse("projectmanager-list")


class ProjectUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = 'projectmanagement_app.change_project'
    model = Project
    fields = [
        "name", 
        "description", 
        "department", 
        "manager", 
        "status",
    ]

    def get_success_url(self):
        return reverse("project-detail", args=[self.object.pk])


class TaskUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = 'projectmanagement_app.change_task'
    model = Task
    fields = [
        "project",
        "name",
        "due_date",
        "status",
        "person_assigned",
        "additional_information",
        "priority",
    ]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        project_id = self.object.project_id
        context["project_id"] = project_id
        return context

    def get_success_url(self):
        return reverse("task-list", args=[self.object.project_id])


class ProjectManagerUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = 'projectmanagement_app.change_projectmanager'
    model = ProjectManager
    fields = [
        "name", 
        "department",
    ]

    success_url = reverse_lazy('projectmanager-list')


class ProjectDelete(PermissionRequiredMixin, DeleteView):
    permission_required = 'projectmanagement_app.delete_project'
    model = Project
    success_url = reverse_lazy('index')


class TaskDelete(PermissionRequiredMixin, DeleteView):
    permission_required = 'projectmanagement_app.delete_task'
    model = Task
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        project_id = self.kwargs["project_id"]
        context["project_id"] = project_id
        return context

    def get_success_url(self):
        return reverse("task-list", args=[self.object.project_id])


class ProjectManagerDelete(PermissionRequiredMixin, DeleteView):
    permission_required = 'projectmanagement_app.delete_projectmanager'
    model = ProjectManager
    success_url = reverse_lazy('projectmanager-list')

    # check if there are any projects assigned to the manager, the manager cannot be deleted if there are some
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        number_assigned_projects = Project.objects.filter(manager=self.kwargs["pk"]).count()
        context["number_assigned_projects"] = number_assigned_projects
        return context


def statistics(request):
    num_projects = Project.objects.all().count()
    num_tasks = Task.objects.all().count()
    num_completed_tasks = Task.objects.filter(status='CO').count()
    try:
        percentage_completed_tasks = "{:.0%}".format(num_completed_tasks/num_tasks)
    except:
        percentage_completed_tasks = "0%"
    num_completed_projects = Project.objects.filter(status='CO').count()
    try:
        percentage_completed_projects = "{:.0%}".format(num_completed_projects/num_projects)
    except:
        percentage_completed_projects = "0%"

    context = {
        'num_projects': num_projects,
        'num_tasks': num_tasks,
        'num_completed_tasks': num_completed_tasks,
        'percentage_completed_tasks': percentage_completed_tasks,
        'num_completed_projects': num_completed_projects,
        'percentage_completed_projects': percentage_completed_projects,
    }

    return render(request, 'statistics.html', context=context)


def managers_projects(request, manager_id):
    projects = Project.objects.filter(manager=manager_id)
    manager_name = ProjectManager.objects.get(id=manager_id)
    context = {
        'projects': projects,
        'manager_id': manager_id,
        'manager_name': manager_name,
    }
    return render(request, 'managers_projects.html', context=context)


def custom_error_403(request, exception):
    return render(request, '403.html', {})

def custom_error_404(request, exception):
    return render(request, '404.html', {})

projectmanagement_app/templates/projectmanagement_app/project_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <h4>Delete Project</h4>
    <p style="padding-bottom: 35px;" class="fs-3">
        <span class="text-danger msg">Are you sure you want to delete the project?</span><br>
        <i>{{ object.name }}</i>
</p>
    <form method="POST" style="display: inline;">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Yes</button>
    </form>
    <nobr>
        <button class="btn btn-danger" onclick="location.href='{% url "index" %}';">Cancel</button>
    {% endblock %}

projectmanagement_app/templates/projectmanagement_app/project_detail.html
{% extends "base.html" %}
{% block content %}
    <h4>Project: {{ project.name }}</h4>
    <table class="table table-borderless" style="width:70%;">
        <tbody>
            <tr>
                <td>Description:</td>
                <td>{{ project.description }}</td>
            </tr>
            <tr>
                <td>Project Manager:</td>
                <td>{{ project.manager }}</td>
            </tr>
            <tr>
                <td>Department:</td>
                <td>{{ project.manager.department }}</td>
            </tr>
            <tr>
                <td>Progress:</td>
                <td>
                    {% if num_tasks %}
                        {{ percent_completed_tasks }} ({{ num_completed_tasks }} task{{ num_completed_tasks|pluralize }} completed out of {{ project.task_set.all.count }})
                    {% else %}
                        N/A (no tasks added)
                    {% endif %}
                </td>
            </tr>
        </tbody>
    </table>
    {% if perms.projectmanagement_app.change_project %}
        <button class="btn btn-primary"
                onclick="location.href='{% url "project-update" project_id %}';">Edit project details</button>
    {% endif %}
    {% if perms.projectmanagement_app.delete_project %}
        <button class="btn btn-danger"
                onclick="location.href='{% url "project-delete" project_id %}';">Delete the project</button>
    {% endif %}
{% endblock %}

projectmanagement_app/templates/projectmanagement_app/project_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <h4>ADD A NEW PROJECT</h4>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <div style="padding-top:30px;">
            <button type="submit" class="btn btn-primary">Submit</button>
            <button class="btn btn-danger" onclick="location.href='{% url "index" %}';">Cancel</button>
        </div>
    </form>
{% endblock %}

projectmanagement_app/templates/projectmanagement_app/project_list.html
{% extends "base.html" %}
{% block content %}
    {% if project_list %}
        <h4>ALL PROJECTS</h4>
        <table class="table table-striped table-dark"
               style="width:80%;
                      margin-bottom:35px">
            <thead>
                <tr>
                    <th scope="col">PROJECT NAME</th>
                    <th scope="col">STATUS</th>
                    <th scope="col">Manager</th>
                    <th scope="col">DEPARTMENT</th>
                </tr>
            </thead>
            <tbody>
                {% for project in project_list %}
                    <tr>
                        <td style="width: 50%">
                            <a href="{% url "task-list" project.id %}">{{ project.name }}</a>
                        </td>
                        <td {% if project.status == 'NS' %} style="color:#6c6a75;" {% elif project.status == 'IP' %} style="color:#3183b6;" {% elif project.status == 'CO' %} style="color:green;" {% elif project.status == 'CA' %} style="color:#B20000;" {% endif %}>
                            {{ project.get_status_display }}
                        </td>
                        <td>{{ project.manager }}</td>
                        <td>{{ project.manager.department }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>There are no projects.</p>
    {% endif %}
    {% if perms.projectmanagement_app.add_project %}
        <button class="btn btn-primary"
                onclick="location.href='{% url "project-create" %}';">Add a new project</button>
    {% endif %}
{% endblock %}

projectmanagement_app/templates/projectmanagement_app/projectmanager_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <h4>Delete Manager</h4>
    {% if number_assigned_projects %}
        <p style="padding-bottom: 35px;" class="text-danger msg">
            You can't delete this manager because the manager is assigned to some projects.
            <br>
            Please update project details so that this manager is not assigned to any projects.
        </p>
    {% else %}
    <p style="padding-bottom: 35px;" class="fs-3">
        <span class="text-danger msg">Are you sure you want to delete the manager from database?</span><br>
</p>
        <form method="POST" style="display: inline;">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">Yes</button>
        </form>
        <nobr>
        {% endif %}
        <button class="btn btn-danger"
                onclick="location.href='{% url "projectmanager-list" %}';">Cancel</button>
    {% endblock %}

projectmanagement_app/templates/projectmanagement_app/projectmanager_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <h4>ADD A NEW MANAGER</h4>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <div style="padding-top:30px;">
            <button type="submit" class="btn btn-primary">Submit</button>
            <button class="btn btn-danger"
                    onclick="location.href='{% url "projectmanager-list" %}';">Cancel</button>
        </div>
    </form>
{% endblock %}

projectmanagement_app/templates/projectmanagement_app/projectmanager_list.html
{% extends "base.html" %}
{% block content %}
    {% if projectmanager_list %}
        <h4>MANAGERS</h4>
        <table class="table table-striped table-dark"
               style="width:50%;
                      margin-bottom:35px">
            <thead>
                <tr>
                    <th scope="col">NAME</th>
                    <th scope="col">DEPARTMENT</th>
                </tr>
            </thead>
            <tbody>
                {% for manager in projectmanager_list %}
                    <tr>
                        <td>
                            <a href="{% url "managers-projects" manager.id %}">{{ manager.name }}</a>
                        </td>
                        <td>{{ manager.department }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>There are no managers.</p>
    {% endif %}
    {% if perms.projectmanagement_app.add_projectmanager %}
        <button class="btn btn-primary"
                onclick="location.href='{% url "projectmanager-create" %}';">Add a new manager</button>
    {% endif %}
{% endblock %}

projectmanagement_app/templates/projectmanagement_app/task_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <h4>Delete Task</h4>
    <p style="padding-bottom: 35px;" class="fs-3">
            <span class="text-danger msg">Are you sure you want to delete the task?</span><br>
            <i>{{ object.name }}</i>
    </p>
                
        <form method="POST" style="display: inline;">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary">Yes</button>
                    </form>
                    <nobr>
                        <button class="btn btn-danger"
                                onclick="location.href='{% url "task-list" project_id %}';">Cancel</button>
                    {% endblock %}

projectmanagement_app/templates/projectmanagement_app/task_detail.html
{% extends "base.html" %}
{% block content %}
    <h4>Task: {{ task.name }}</h4>
    <table class="table table-borderless" style="width:40%; margin-bottom:35px;">
        <tbody>
            <tr>
                <td>Due date:</td>
                <td>{{ task.due_date }}</td>
            </tr>
            <tr>
                <td>Status:</td>
                <td>{{ task.get_status_display }}</td>
            </tr>
            <tr>
                <td>Priority:</td>
                <td>{{ task.get_priority_display }}</td>
            </tr>
            <tr>
                <td>Person assigned:</td>
                <td>{{ task.person_assigned }}</td>
            </tr>
            <tr>
                <td>Additional information:</td>
                {% if task.additional_information %}
                    <td>{{ task.additional_information }}</td>
                {% else %}
                    <td>-</td>
                {% endif %}
            </tr>
        </tbody>
    </table>
    {% if perms.projectmanagement_app.change_task %}
        <button class="btn btn-outline-primary"
                onclick="location.href='{% url "task-update" project_id task_id %}';">Edit the task</button>
    {% endif %}
    {% if perms.projectmanagement_app.delete_task %}
        <button class="btn btn-danger"
                onclick="location.href='{% url "task-delete" project_id task_id %}';">Delete the task</button>
    {% endif %}
{% endblock %}

projectmanagement_app/templates/projectmanagement_app/task_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <h4 style="padding-bottom:30px;">EDIT THE TASK</h4>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <div style="padding-top:30px;">
            <button type="submit" class="btn btn-primary">Submit</button>
            <button class="btn btn-danger"
                    onclick="location.href='{% url "task-list" project_id %}';">Cancel</button>
        </div>
    </form>
{% endblock %}

projectmanagement_app/templates/projectmanagement_app/task_list.html
{% extends "base.html" %}
{% block content %}
    {% if task_list %}
        <h4 style="padding-bottom: 0px;">TASK LIST</h4>
        <h5>Project: {{ project_name }}</h5>
        <table class="table table-striped table-dark"
               style="width:80%;
                      margin-bottom:35px">
            <thead>
                <tr>
                    <th scope="col">TASK NAME</th>
                    <th scope="col">DUE DATE</th>
                    <th scope="col">STATUS</th>
                    <th scope="col">PERSON ASSIGNED</th>
                </tr>
            </thead>
            <tbody>
                {% for task in task_list %}
                    <tr>
                        <td>
                            <a href="{% url "task-detail" task.project_id task.id %}">{{ task.name }}</a>
                        </td>
                        <td>{{ task.due_date | date:"d-M-y" }}</td>
                        <td {% if task.status == 'NS' %} style="color:#6c6a75" {% elif task.status == 'IP' %} style="color:#3183b6;" {% elif task.status == 'CO' %} style="color:green;" {% elif task.status == 'CA' %} style="color:#B20000;" {% endif %}>
                            {{ task.get_status_display }}
                        </td>
                        <td>{{ task.person_assigned }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>There are no tasks.</p>
    {% endif %}
    {% if perms.projectmanagement_app.add_task %}
        <button class="btn btn-primary"
                onclick="location.href='{% url "task-create" project_id %}';">Add a new task</button>
    {% endif %}
    <button class="btn btn-primary"
            onclick="location.href='{% url "project-detail" project_id %}';">Project details</button>
{% endblock %}